services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://localhost"
    volumes:
      - ./vw-data/:/data/
    ports:
      - "8000:80"

  postgres:
    image: postgres:15
    container_name: notes_pg
    restart: always
    environment:
      POSTGRES_DB: health_db
      POSTGRES_USER: health_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5433:5432"
volumes:
  pgdata:
